site_name: Cookiecutter Chic Pypackage
site_url: https://ibmw.github.io/cookiecutter-chic-pypackage
repo_url: https://github.com/ibmw/cookiecutter-chic-pypackage
repo_name: ibmw/cookiecutter-chic-pypackage
nav:
  - Introduction: index.md
  - Usage: usage.md
  - Template Parameters: template_params.md
  - History: history.md

theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
plugins:
  - include-markdown
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibmw
      name: Github
    - icon: material/email
      link: "mailto:contact@olivier-maillot.fr"
