version: "3.9"

services:

  devcontainer:
    build:
      context: .
      target: dev
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-{{ cookiecutter.python_version }}}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      - POETRY_PYPI_TOKEN_PYPI
    volumes:
      - ..:/workspaces
      - command-history-volume:/home/user/.history/

  dev:
    extends: devcontainer
    stdin_open: true
    tty: true
    entrypoint: []
    command:
      [
        "sh",
        "-c",
        "sudo chown user $$SSH_AUTH_SOCK && cp --update /opt/build/poetry/poetry.lock /workspaces/{{ cookiecutter.__package_name_kebab_case }}/ && mkdir -p /workspaces/{{ cookiecutter.__package_name_kebab_case }}/.git/hooks/ && cp --update /opt/build/git/* /workspaces/{{ cookiecutter.__package_name_kebab_case }}/.git/hooks/ && zsh"
      ]
    environment:
      - POETRY_PYPI_TOKEN_PYPI
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}
    ports:
      - "8000"
    {%- endif %}
    volumes:
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh/known_hosts:/home/user/.ssh/known_hosts
      - ${SSH_AGENT_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:/run/host-services/ssh-auth.sock
    profiles:
      - dev
  {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int or cookiecutter.with_typer_cli|int %}

  app:
    build:
      context: .
      target: app
    tty: true
    {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}
    ports:
      - "8000:8000"
    {%- endif %}
    profiles:
      - app
  {%- endif %}

volumes:
  command-history-volume:
