name: release & publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    name: Publish documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.12]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Removing poetry.lock
        run: rm -rf poetry.lock
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --with dev,test,docs --no-interaction --no-root --sync

      - name: build documentation
        run: poetry run mkdocs build

      - name: publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site
